
[glance]
path = "data/status.json"
poll = 5
pos = "TR"
x_offset = 20
y_offset = 20
alpha = 0.7
tick_stack = "left"
click_through = false
font = "JetBrainsMono NF"
font_size = 12
monitors = "all"

[updater]
output_path = "data/status.json"

[providers.work_outlook]
kind = "outlook"

[providers.work_jira]
kind = "jira"

[providers.github]
kind = "github-gh"

[[entries]]
provider = "work_outlook"
label = "email/inbox"
icon = "󰇮"
thresholds = { low = 5, medium = 15, high = 30 }
requests = [
  { folders = ["6"] }
]

[[entries]]
provider = "github"
label = "reviews"
icon = ""
thresholds = { low = 1, medium = 3, high = 5 }
requests = [
  { args = ["--state=open", "--assignee=@me"] },
  { args = ["--state=open", "--review-requested=@me"] }
]
